import assert from "node:assert/strict";
import fs from "node:fs";
import { network } from "hardhat";
import { getAddress, zeroAddress } from "viem";

const proxy = "0x2Bb7F1bF9FF5e3DFF41CF42A3Cccb47D9317b7D4";
const slot = "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc";
const { viem } = await network.create();
const client = await viem.getPublicClient();
const [wallet] = await viem.getWalletClients();
assert.equal(await client.getChainId(), 11155111);
const auction = await viem.getContractAt("MetaNFTAuctionUUPS", proxy);
const owner = await auction.read.owner();
const count = await auction.read.auctionId();
const priorImplementation = await client.getStorageAt({ address: proxy, slot });
console.log("Proxy:", proxy);
console.log("Owner:", owner);
console.log("Deployer:", wallet.account.address);
console.log("Auction count:", count.toString());
console.log("Implementation slot:", priorImplementation);
if (process.env.AUCTION_UPGRADE_EXECUTE !== "1") process.exit(0);
assert.equal(getAddress(wallet.account.address), getAddress(owner), "Configured signer is not proxy owner; upgrade requires owner's signature");
const tokens = new Set([zeroAddress, "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"]);
const auctionsBefore = [];
for (let id = 0n; id < count; id++) {
  const entry = await auction.read.auctions([id]);
  auctionsBefore.push(entry);
  tokens.add(entry[7]);
}
const oraclesBefore = await Promise.all([...tokens].map(async token => [token, await auction.read.tokenToOracle([token as `0x${string}`])] as const));
const deploymentId = process.env.AUCTION_IMPLEMENTATION_DEPLOYMENT ?? "meta-nft-auction-force-end-20261009";
const implementations = JSON.parse(fs.readFileSync(`ignition/deployments/${deploymentId}/deployed_addresses.json`, "utf8"));
const implementation = await viem.getContractAt("MetaNFTAuctionUUPS", implementations["MetaNFTAuctionImplementationModule#MetaNFTAuctionUUPS"]);
const recordPath = `ignition/deployments/meta-nft-auction-sepolia-upgrade-${implementation.address.toLowerCase()}.json`;
const record = { chainId: 11155111, proxy, implementation: implementation.address, previousImplementation: priorImplementation, owner, status: "implementation-deployed", transaction: "" };
fs.writeFileSync(recordPath, JSON.stringify(record, null, 2) + "\n");
console.log("New implementation:", implementation.address);
const hash = await auction.write.upgradeToAndCall([implementation.address, "0x"]);
record.transaction = hash;
record.status = "upgrade-submitted";
fs.writeFileSync(recordPath, JSON.stringify(record, null, 2) + "\n");
const receipt = await client.waitForTransactionReceipt({ hash });
assert.equal(receipt.status, "success");
const after = await client.getStorageAt({ address: proxy, slot });
assert.equal(after?.slice(-40).toLowerCase(), implementation.address.slice(2).toLowerCase());
assert.equal(await auction.read.owner(), owner);
assert.equal(await auction.read.auctionId(), count);
for (const [token, oracle] of oraclesBefore) assert.equal(await auction.read.tokenToOracle([token as `0x${string}`]), oracle);
for (let id = 0n; id < count; id++) assert.deepEqual(await auction.read.auctions([id]), auctionsBefore[Number(id)]);
record.status = "upgraded-and-checked";
fs.writeFileSync(recordPath, JSON.stringify(record, null, 2) + "\n");
console.log("Upgraded and checked existing owner, auction records, payment-token oracles and implementation slot:", hash);
